# Generated by Django 4.1.6 on 2023-05-08 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_picture_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('number_of_cores', models.PositiveIntegerField()),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('frequency', models.PositiveIntegerField()),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('is_notebook', models.BooleanField()),
            ],
            bases=('products.product',),
        ),
    ]
