# Generated by Django 4.1.6 on 2023-05-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cpu_gpu_pc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPU',
        ),
    ]
