# Generated by Django 4.1.6 on 2023-05-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CPU', 'CPU'), ('PC', 'PC')], max_length=3),
        ),
    ]
